# General Tagging

variable "tags" {
  description = "Map of tags generated by the `aws-resource-tags` module. (Use the common format.)"
  type        = map(string)
}

# https://developer.hashicorp.com/terraform/language/expressions/strings#indented-heredocs
variable "replace_drop_filter" {
  type        = string
  description = "Replaces the default drop filter. You are required to assign the value using indented Heredocs."
  default     = ""
}

# https://github.com/aws/aws-for-fluent-bit/releases
variable "aws_for_fluent_bit_image_version" {
  type        = string
  description = "Specify the tag to be used for The AWS for Fluent Bit image. See https://github.com/aws/aws-for-fluent-bit/releases"
  default     = "2.31.12.20230727"
}

variable "service_name" {
  type        = string
  description = "ECS Service Name."
  default     = ""
}
